export function normalizeContact(value, role, source) {
	if (!value) return undefined;
	const contact =
		typeof value === "string"
			? {
					name: value.replace(/<[^>]*>|\([^)]*\)/gu, "").trim(),
					email: value.match(/<([^>]*)>/u)?.[1]?.trim(),
				}
			: { name: value.name, email: value.email };
	const name =
		typeof contact.name === "string" ? contact.name.trim() : undefined;
	const email =
		typeof contact.email === "string" ? contact.email.trim() : undefined;
	return name || email ? { role, name, email, source } : undefined;
}

export function npmContacts(metadata) {
	return [
		normalizeContact(
			metadata.publisher,
			"Publisher",
			"package.json: publisher",
		),
		normalizeContact(metadata.author, "Author", "package.json: author"),
		...(Array.isArray(metadata.maintainers) ? metadata.maintainers : []).map(
			(value) =>
				normalizeContact(value, "Maintainer", "package.json: maintainers"),
		),
	].filter(Boolean);
}

export function contactLines(contacts = []) {
	return contacts.flatMap(({ role, name, email, source }) => [
		...(name ? [`${role}: ${name}`] : []),
		...(email ? [`${role} email: ${email}`] : []),
		...(source && (name || email) ? [`Metadata source: ${source}`] : []),
	]);
}

export function compactContactLines(contacts = []) {
	return contacts.flatMap(({ role, name, email }) => {
		if (name && email) return [`${role} <email>: ${name} <${email}>`];
		if (name) return [`${role}: ${name}`];
		if (email) return [`${role} email: ${email}`];
		return [];
	});
}

export function escapeHtml(value) {
	return String(value)
		.replaceAll("&", "&amp;")
		.replaceAll("<", "&lt;")
		.replaceAll(">", "&gt;")
		.replaceAll('"', "&quot;")
		.replaceAll("'", "&#39;");
}

export function renderHtmlDocument(npmPackages, androidArtifacts) {
	const blocks = [];
	for (const component of [...npmPackages, ...androidArtifacts]) {
		const key = component.key ?? component.coordinate;
		const metadata = [
			`Declared license: ${component.license}`,
			...contactLines(component.contacts),
			...(component.homepage ? [`Homepage: ${component.homepage}`] : []),
			...(component.repository ? [`Repository: ${component.repository}`] : []),
			...(component.pomUrl ? [`Maven POM: ${component.pomUrl}`] : []),
			...(component.pomLicenses ?? []).map(
				({ name, url }) =>
					`Declared: ${name ?? "unnamed license"}${url ? ` (${url})` : ""}`,
			),
			...(component.licenseConflict
				? [`Warning: ${component.licenseConflict.explanation}`]
				: []),
			...(component.licenseFileFallback
				? [
						`License file fallback: ${component.licenseFileFallback.sourceKey}. ${component.licenseFileFallback.explanation}`,
					]
				: []),
		];
		const files = component.legalFiles ?? [
			{ name: "License texts", text: component.licenseNotices },
			...(component.embeddedNoticeFiles ?? []).map(({ path, text }) => ({
				name: `embedded ${path}`,
				text,
			})),
		];
		blocks.push(`<details data-component="${escapeHtml(key)}"><summary>${escapeHtml(key)} <span>${escapeHtml(component.license)}</span></summary>
<div class="content"><h3>Component information</h3><ul>${metadata.map((line) => `<li>${escapeHtml(line)}</li>`).join("\n")}</ul>
${files.map(({ name, text }) => `<section><h3>${escapeHtml(name)}</h3><pre>${escapeHtml(text)}</pre></section>`).join("\n")}</div></details>`);
	}
	return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Third-party software notices</title>
</head><body><main>
<h1>Third-party software notices</h1>
<p>Generated by scripts/generate_third_party_licenses.mjs. Do not edit manually.</p>
<p>Third-party software included in the application release: npm production dependencies and resolved Android runtime artifacts. Development-only dependencies are excluded.</p>
<p>Each component remains subject to its own applicable license terms. These licenses and notices apply only to the respective third-party components and do not alter, replace, or limit the AGPL-3.0-only license terms applicable to this application's own code.</p>
<p>Select a component to expand its metadata and full license and notice texts.</p>
<h2>npm runtime packages (${npmPackages.length})</h2>
${blocks.slice(0, npmPackages.length).join("\n")}
<h2>Android runtime artifacts (${androidArtifacts.length})</h2>
${blocks.slice(npmPackages.length).join("\n")}
</main></body></html>
`;
}
